# Generated by Django 2.1.5 on 2019-02-11 09:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama_Challange', models.TextField(max_length=255)),
                ('banyak_soal', models.CharField(max_length=25)),
                ('bobot_nilai', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='direksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama_Lengkap', models.TextField(max_length=255)),
                ('Nomor_Telepon', models.TextField(max_length=25)),
                ('Jabatan', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='live_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama_live_code', models.TextField(max_length=255)),
                ('banyak_soal', models.CharField(max_length=25)),
                ('bobot_nilai', models.CharField(max_length=25)),
                ('tanggal_pelaksanaan', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='mata_pelajaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelajaran', models.TextField(max_length=255)),
                ('jadwal_dimulai', models.DateTimeField(default=django.utils.timezone.now)),
                ('jadwal_berakhir', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama_Lengkap', models.TextField(max_length=255)),
                ('Nomor_Telepon', models.CharField(max_length=25)),
                ('Nomor_absen', models.CharField(max_length=2)),
                ('Nilai_rerata', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama_Lengkap', models.TextField(max_length=255)),
                ('Nomor_Telepon', models.CharField(max_length=25)),
                ('Ma_Pel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATA.mata_pelajaran')),
            ],
        ),
        migrations.AddField(
            model_name='live_code',
            name='Pelajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATA.mata_pelajaran'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='Pelajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATA.mata_pelajaran'),
        ),
    ]
