# Generated by Django 2.1.5 on 2019-02-11 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dokter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nomor_telepon', models.TextField(max_length=25)),
                ('bidang', models.TextField(max_length=100)),
                ('jadwal_praktek', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='pasien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nomor_telepon', models.TextField(max_length=25)),
                ('alamat', models.TextField(max_length=255)),
                ('keluhan', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='resep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('total_harga', models.CharField(max_length=25)),
                ('kumpulan_obat', models.TextField(max_length=255)),
            ],
        ),
    ]
