# Generated by Django 2.1.5 on 2019-02-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rumah_sakit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='obat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField(max_length=50)),
                ('kandungan', models.TextField(max_length=255)),
                ('khasiat', models.TextField(max_length=255)),
            ],
        ),
    ]
